### ISSUE TITLE
When the global resource scheduler gets shut down, all the scheduler processes do not close automatically

### ISSUE THREAD

**Issue by jshaofuturewei** [CentaurusInfra/global-resource-scheduler#259]

**Comment by kimeunju108** [comment]
This is fixed and will make a new PR soon

**Comment by cathyhongzhang** [comment]
will upload PR today

**Comment by jshaofuturewei** [comment]
The previous PR #264 did not fix the issue. I created another PR #268  to fix it.

**Comment by cathyhongzhang** [comment]
completed
